# Generated by Django 5.1.15 on 2026-03-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('bug', 'Bug Report'), ('billing', 'Billing Issue'), ('gameplay', 'Gameplay Question'), ('abuse', 'Abuse Report'), ('feedback', 'Feedback')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('ai_category', models.CharField(blank=True, choices=[('bug', 'Bug Report'), ('billing', 'Billing Issue'), ('gameplay', 'Gameplay Question'), ('abuse', 'Abuse Report'), ('feedback', 'Feedback')], max_length=20)),
                ('ai_response', models.TextField(blank=True)),
                ('agent_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
